# Generated by Django 3.2.23 on 2024-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='default_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='default_full_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
