# Generated by Django 3.2.23 on 2023-12-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_purpose', models.CharField(choices=[('', 'Reason for Contact'), ('PRODUCT', 'Product Enquiry'), ('ORDER', 'Order Enquiry'), ('CS', 'Customer Service'), ('SUGGESTIONS', 'Suggestions'), ('OTHER', 'Other')], max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=44)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
    ]
