# Generated by Django 3.2.23 on 2023-12-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_submitted'], 'verbose_name': 'Messages from User'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_purpose',
            field=models.CharField(choices=[('', 'Reason for Contact'), ('Product Enquiry', 'Product Enquiry'), ('Order Enquiry', 'Order Enquiry'), ('Customer Service', 'Customer Service'), ('Suggestions', 'Suggestions'), ('Other', 'Other')], max_length=24),
        ),
    ]
