# Generated by Django 3.2.23 on 2023-12-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20231220_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_purpose',
            field=models.CharField(choices=[('', 'Reason for Contact'), ('Product Enquiry', 'Product Enquiry'), ('Order Enquiry', 'Order Enquiry'), ('Customer Service', 'Customer Service'), ('Diverse Design', 'Diverse Design Event'), ('Complaint', 'Complaint'), ('Feedback', 'Feedback'), ('Other', 'Other')], max_length=24),
        ),
    ]
