# Generated by Django 3.2.23 on 2023-12-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
