# Generated by Django 3.2.23 on 2023-11-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.95, max_digits=10),
        ),
    ]
