# Generated by Django 3.2.23 on 2023-11-26 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231125_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default=django.utils.crypto.get_random_string, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
