# Generated by Django 3.2.23 on 2023-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes_available',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
