# Generated by Django 3.2.23 on 2023-12-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
