# Generated by Django 3.2.23 on 2023-12-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created_at'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
